package it.deloitte.postrxade.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * ISO 3166-1 country codes. Constant identifier is the Alpha-3 code; fields
 * carry the 3-digit zero-padded numeric code and the English country name.
 */
@Getter
public enum CountryNumericCodeEnum {

    AFG("004", "Afghanistan"),
    ALA("248", "Åland Islands"),
    ALB("008", "Albania"),
    DZA("012", "Algeria"),
    ASM("016", "American Samoa"),
    AND("020", "Andorra"),
    AGO("024", "Angola"),
    AIA("660", "Anguilla"),
    ATA("010", "Antarctica"),
    ATG("028", "Antigua and Barbuda"),
    ARG("032", "Argentina"),
    ARM("051", "Armenia"),
    ABW("533", "Aruba"),
    AUS("036", "Australia"),
    AUT("040", "Austria"),
    AZE("031", "Azerbaijan"),
    BHS("044", "Bahamas"),
    BHR("048", "Bahrain"),
    BGD("050", "Bangladesh"),
    BRB("052", "Barbados"),
    BLR("112", "Belarus"),
    BEL("056", "Belgium"),
    BLZ("084", "Belize"),
    BEN("204", "Benin"),
    BMU("060", "Bermuda"),
    BTN("064", "Bhutan"),
    BOL("068", "Bolivia"),
    BES("535", "Bonaire, Sint Eustatius and Saba"),
    BIH("070", "Bosnia and Herzegovina"),
    BWA("072", "Botswana"),
    BVT("074", "Bouvet Island"),
    BRA("076", "Brazil"),
    IOT("086", "British Indian Ocean Territory"),
    BRN("096", "Brunei Darussalam"),
    BGR("100", "Bulgaria"),
    BFA("854", "Burkina Faso"),
    BDI("108", "Burundi"),
    CPV("132", "Cabo Verde"),
    KHM("116", "Cambodia"),
    CMR("120", "Cameroon"),
    CAN("124", "Canada"),
    CYM("136", "Cayman Islands"),
    CAF("140", "Central African Republic"),
    TCD("148", "Chad"),
    CHL("152", "Chile"),
    CHN("156", "China"),
    CXR("162", "Christmas Island"),
    CCK("166", "Cocos (Keeling) Islands"),
    COL("170", "Colombia"),
    COM("174", "Comoros"),
    COD("180", "Congo (Democratic Republic)"),
    COG("178", "Congo"),
    COK("184", "Cook Islands"),
    CRI("188", "Costa Rica"),
    CIV("384", "Côte d'Ivoire"),
    HRV("191", "Croatia"),
    CUB("192", "Cuba"),
    CUW("531", "Curaçao"),
    CYP("196", "Cyprus"),
    CZE("203", "Czechia"),
    DNK("208", "Denmark"),
    DJI("262", "Djibouti"),
    DMA("212", "Dominica"),
    DOM("214", "Dominican Republic"),
    ECU("218", "Ecuador"),
    EGY("818", "Egypt"),
    SLV("222", "El Salvador"),
    GNQ("226", "Equatorial Guinea"),
    ERI("232", "Eritrea"),
    EST("233", "Estonia"),
    SWZ("748", "Eswatini"),
    ETH("231", "Ethiopia"),
    FLK("238", "Falkland Islands"),
    FRO("234", "Faroe Islands"),
    FJI("242", "Fiji"),
    FIN("246", "Finland"),
    FRA("250", "France"),
    GUF("254", "French Guiana"),
    PYF("258", "French Polynesia"),
    ATF("260", "French Southern Territories"),
    GAB("266", "Gabon"),
    GMB("270", "Gambia"),
    GEO("268", "Georgia"),
    DEU("276", "Germany"),
    GHA("288", "Ghana"),
    GIB("292", "Gibraltar"),
    GRC("300", "Greece"),
    GRL("304", "Greenland"),
    GRD("308", "Grenada"),
    GLP("312", "Guadeloupe"),
    GUM("316", "Guam"),
    GTM("320", "Guatemala"),
    GGY("831", "Guernsey"),
    GIN("324", "Guinea"),
    GNB("624", "Guinea-Bissau"),
    GUY("328", "Guyana"),
    HTI("332", "Haiti"),
    HMD("334", "Heard Island and McDonald Islands"),
    VAT("336", "Holy See"),
    HND("340", "Honduras"),
    HKG("344", "Hong Kong"),
    HUN("348", "Hungary"),
    ISL("352", "Iceland"),
    IND("356", "India"),
    IDN("360", "Indonesia"),
    IRN("364", "Iran"),
    IRQ("368", "Iraq"),
    IRL("372", "Ireland"),
    IMN("833", "Isle of Man"),
    ISR("376", "Israel"),
    ITA("380", "Italy"),
    JAM("388", "Jamaica"),
    JPN("392", "Japan"),
    JEY("832", "Jersey"),
    JOR("400", "Jordan"),
    KAZ("398", "Kazakhstan"),
    KEN("404", "Kenya"),
    KIR("296", "Kiribati"),
    PRK("408", "Korea (Democratic People's Republic)"),
    KOR("410", "Korea (Republic)"),
    KWT("414", "Kuwait"),
    KGZ("417", "Kyrgyzstan"),
    LAO("418", "Lao People's Democratic Republic"),
    LVA("428", "Latvia"),
    LBN("422", "Lebanon"),
    LSO("426", "Lesotho"),
    LBR("430", "Liberia"),
    LBY("434", "Libya"),
    LIE("438", "Liechtenstein"),
    LTU("440", "Lithuania"),
    LUX("442", "Luxembourg"),
    MAC("446", "Macao"),
    MKD("807", "North Macedonia"),
    MDG("450", "Madagascar"),
    MWI("454", "Malawi"),
    MYS("458", "Malaysia"),
    MDV("462", "Maldives"),
    MLI("466", "Mali"),
    MLT("470", "Malta"),
    MHL("584", "Marshall Islands"),
    MTQ("474", "Martinique"),
    MRT("478", "Mauritania"),
    MUS("480", "Mauritius"),
    MYT("175", "Mayotte"),
    MEX("484", "Mexico"),
    FSM("583", "Micronesia (Federated States)"),
    MDA("498", "Moldova"),
    MCO("492", "Monaco"),
    MNG("496", "Mongolia"),
    MNE("499", "Montenegro"),
    MSR("500", "Montserrat"),
    MAR("504", "Morocco"),
    MOZ("508", "Mozambique"),
    MMR("104", "Myanmar"),
    NAM("516", "Namibia"),
    NRU("520", "Nauru"),
    NPL("524", "Nepal"),
    NLD("528", "Netherlands"),
    NCL("540", "New Caledonia"),
    NZL("554", "New Zealand"),
    NIC("558", "Nicaragua"),
    NER("562", "Niger"),
    NGA("566", "Nigeria"),
    NIU("570", "Niue"),
    NFK("574", "Norfolk Island"),
    MNP("580", "Northern Mariana Islands"),
    NOR("578", "Norway"),
    OMN("512", "Oman"),
    PAK("586", "Pakistan"),
    PLW("585", "Palau"),
    PSE("275", "Palestine, State of"),
    PAN("591", "Panama"),
    PNG("598", "Papua New Guinea"),
    PRY("600", "Paraguay"),
    PER("604", "Peru"),
    PHL("608", "Philippines"),
    PCN("612", "Pitcairn"),
    POL("616", "Poland"),
    PRT("620", "Portugal"),
    PRI("630", "Puerto Rico"),
    QAT("634", "Qatar"),
    REU("638", "Réunion"),
    ROU("642", "Romania"),
    RUS("643", "Russian Federation"),
    RWA("646", "Rwanda"),
    BLM("652", "Saint Barthélemy"),
    SHN("654", "Saint Helena, Ascension and Tristan da Cunha"),
    KNA("659", "Saint Kitts and Nevis"),
    LCA("662", "Saint Lucia"),
    MAF("663", "Saint Martin (French part)"),
    SPM("666", "Saint Pierre and Miquelon"),
    VCT("670", "Saint Vincent and the Grenadines"),
    WSM("882", "Samoa"),
    SMR("674", "San Marino"),
    STP("678", "Sao Tome and Principe"),
    SAU("682", "Saudi Arabia"),
    SEN("686", "Senegal"),
    SRB("688", "Serbia"),
    SYC("690", "Seychelles"),
    SLE("694", "Sierra Leone"),
    SGP("702", "Singapore"),
    SXM("534", "Sint Maarten (Dutch part)"),
    SVK("703", "Slovakia"),
    SVN("705", "Slovenia"),
    SLB("090", "Solomon Islands"),
    SOM("706", "Somalia"),
    ZAF("710", "South Africa"),
    SGS("239", "South Georgia and South Sandwich Islands"),
    SSD("728", "South Sudan"),
    ESP("724", "Spain"),
    LKA("144", "Sri Lanka"),
    SDN("729", "Sudan"),
    SUR("740", "Suriname"),
    SJM("744", "Svalbard and Jan Mayen"),
    SWE("752", "Sweden"),
    CHE("756", "Switzerland"),
    SYR("760", "Syrian Arab Republic"),
    TWN("158", "Taiwan"),
    TJK("762", "Tajikistan"),
    TZA("834", "Tanzania, United Republic of"),
    THA("764", "Thailand"),
    TLS("626", "Timor-Leste"),
    TGO("768", "Togo"),
    TKL("772", "Tokelau"),
    TON("776", "Tonga"),
    TTO("780", "Trinidad and Tobago"),
    TUN("788", "Tunisia"),
    TUR("792", "Turkey"),
    TKM("795", "Turkmenistan"),
    TCA("796", "Turks and Caicos Islands"),
    TUV("798", "Tuvalu"),
    UGA("800", "Uganda"),
    UKR("804", "Ukraine"),
    ARE("784", "United Arab Emirates"),
    GBR("826", "United Kingdom"),
    UMI("581", "United States Minor Outlying Islands"),
    USA("840", "United States of America"),
    URY("858", "Uruguay"),
    UZB("860", "Uzbekistan"),
    VUT("548", "Vanuatu"),
    VEN("862", "Venezuela"),
    VNM("704", "Viet Nam"),
    VGB("092", "Virgin Islands (British)"),
    VIR("850", "Virgin Islands (U.S.)"),
    WLF("876", "Wallis and Futuna"),
    ESH("732", "Western Sahara"),
    YEM("887", "Yemen"),
    ZMB("894", "Zambia"),
    ZWE("716", "Zimbabwe");

    private final String numericCode;
    private final String countryName;

    private static final Set<String> NUMERIC_CODES = Arrays.stream(values())
            .map(CountryNumericCodeEnum::getNumericCode)
            .collect(Collectors.toUnmodifiableSet());

    CountryNumericCodeEnum(String numericCode, String countryName) {
        this.numericCode = numericCode;
        this.countryName = countryName;
    }

    public static boolean isValidNumericCode(String code) {
        return code != null && NUMERIC_CODES.contains(code);
    }
}
